import { prisma } from "@/lib/prisma";

let ensured = false;

/**
 * Idempotent DDL for the V2 Private Photo Reveal system (docs/V2_PRIVATE_PHOTO_REVEAL_AND_NOTIFICATIONS.md).
 * Same lazy-DDL pattern as the other `ensure*Schema` helpers — this project applies schema growth
 * as raw SQL run before first use rather than a formal migration run against the pooled connection.
 */
export async function ensurePrivatePhotosSchema() {
  if (ensured) return;
  try {
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS private_photo_shares (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        match_request_id BIGINT NOT NULL,
        sender_id BIGINT NOT NULL,
        recipient_id BIGINT NOT NULL,
        photo_ids BIGINT[] NOT NULL,
        status VARCHAR(16) NOT NULL DEFAULT 'shared',
        shared_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        viewing_started_at TIMESTAMPTZ,
        expires_at TIMESTAMPTZ,
        wali_allowed_at TIMESTAMPTZ,
        wali_viewing_started_at TIMESTAMPTZ,
        wali_expires_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);
    await prisma.$executeRawUnsafe(`
      CREATE INDEX IF NOT EXISTS idx_private_photo_shares_recipient
        ON private_photo_shares (match_request_id, recipient_id, shared_at DESC)
    `);
    await prisma.$executeRawUnsafe(`
      CREATE INDEX IF NOT EXISTS idx_private_photo_shares_sender
        ON private_photo_shares (match_request_id, sender_id, recipient_id, shared_at DESC)
    `);
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS private_photo_access_log (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        share_id BIGINT NOT NULL,
        event VARCHAR(32) NOT NULL,
        actor_id BIGINT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);
    await prisma.$executeRawUnsafe(`
      CREATE INDEX IF NOT EXISTS idx_private_photo_access_log_share
        ON private_photo_access_log (share_id, created_at)
    `);
    ensured = true;
  } catch (err) {
    console.error("ensurePrivatePhotosSchema", err);
  }
}
